---
# ====== Application: ApexExpImp =============================
id: 100
identification: 
  name: ApexExpImp
  alias: APEXEXPIMP
  version: Release 1.0

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 1406085355982923

authorization: 
  authorization-scheme: Reader Rights # 1605998413983069
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: USER1

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: ApexExpImp

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Translucent

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: ApexExpImp

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 1606881558983072
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  configuration: 
    build-option: 'Feature: Feedback' # 1603352642983059

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 1607165749983073
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  configuration: 
    build-option: 'Feature: Access Control' # 1603193831983059

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

user-interfaces: 
- # ====== User Interface: Desktop =============================
  id: 1601284637983036
  identification: 
    name: Desktop

  navigation: 
    home-url: 
      url: 'f?p=&APP_ID.:1:&SESSION.'
      page: 1 # Home

    login-url: 
      url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
      page: LOGIN

  navigation-menu: 
    list-template: Side Navigation Menu # 1564169059982999
    template-options: 
    - '#DEFAULT#'
    - t-TreeNav--styleA
    - js-navCollapsed--hidden
    list-position: Side
    list: Navigation Menu # 1406822108982928

  navigation-bar: 
    implementation: List
    list: Navigation Bar # 1600932802983033
    list-template: Navigation Bar # 1563726999982998
    template-options: 
    - '#DEFAULT#'

  javascript: 
    include-jquery-migrate: false

  attributes: 
    theme: Universal Theme # 42
    global-page: 0
    enable-end-users-to-choose-theme-style: false
    add-"built-with-apex"-to-footer: false

